application.properties for AWS connection
spring.application.name=User-app
server.port=8080
spring.datasource.url=jdbc:mysql://user-login-db.c3ouswkiemhp.ap-south-1.rds.amazonaws.com:3306/user-login-db
spring.datasource.username=root
spring.datasource.password=root123@
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


logging.level.root=INFO
logging.file.name=/home/ec2-user/app.log
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.address=0.0.0.0
